### ISSUE TITLE
Illegal character SPACE

### ISSUE THREAD

**Issue by popstick** [novalagung/httpsproxy2http#1]
Hi, this is perfect for what I need. However is it possible to allow %20 spaces in the parameters? 

Bad Message 400
reason: Illegal character SPACE=' '

https://httpsproxy2http.novalagung.com/reverse/173.230.134.133:8045/translate?q=space%20here&source=en&target=tdt

**Comment by novalagung** [comment]
it should be possible. I'll try to take a look tonight

**Comment by novalagung** [comment]
@popstick try again. it should be working now

**Comment by popstick** [comment]
Thank you novalagung. Very much appreciated.
